apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-service
  description: My awesome service
  annotations:
    github.com/project-slug: 11thfeb/backstage-test
spec:
  type: service
  lifecycle: production
  owner: admin
  system: my-system
